services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: signaling-server

    restart: unless-stopped

    ports:
      - "3002:3002"

    environment:
      NODE_ENV: production

    valumes:
      - ./data:/app/data
